services:
  - type: web
    name: f1-telegram-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: F1_API_URL
        value: https://f1api.dev/api 